name: Generate GitHub stats SVGs

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch: {}

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate stats images
        uses: jstrieb/github-stats@master
        with:
          username: VanshSharmaPES
          access_token: ${{ secrets.ACCESS_TOKEN }}
          exclude_repos: ""
          exclude_langs: ""

      - name: Commit generated files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add generated/
          git diff --staged --quiet || git commit -m "Update generated stats"
          git push
